# Generated by Django 2.2.5 on 2019-09-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', max_length=20, verbose_name='Status')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('email', models.EmailField(max_length=70, verbose_name='Email')),
                ('text', models.TextField(max_length=1000, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'GuestBook',
                'verbose_name_plural': 'GuestBooks',
            },
        ),
    ]
